// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:async' as prefix2;
import 'dart:core';

import 'package:dio/src/dio.dart' as prefix1;
import 'package:dio/src/options.dart' as prefix3;
// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:teste_dart_flutter/teste.dart' as prefix0;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.MyReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'APIClient',
            r'.APIClient',
            134217735,
            0,
            const prefix0.MyReflectable(),
            const <int>[6, 7, 8, 9, 10, 11],
            const <int>[12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 20, 6, 8, 9],
            const <int>[7],
            -1,
            {r'instance': () => prefix0.APIClient.instance},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'Foto',
            r'.Foto',
            134217735,
            1,
            const prefix0.MyReflectable(),
            const <int>[1, 22, 23],
            const <int>[12, 13, 14, 15, 16, 21],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({foto}) => b ? prefix0.Foto(foto: foto) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix0.Foto.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'Usuario',
            r'.Usuario',
            134217735,
            2,
            const prefix0.MyReflectable(),
            const <int>[2, 3, 4, 5, 28, 29],
            const <int>[12, 13, 14, 15, 16, 24, 25, 26, 27],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({nome, matricula, email, foto}) => b
                  ? prefix0.Usuario(
                      email: email,
                      foto: foto,
                      matricula: matricula,
                      nome: nome)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix0.Usuario.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'dart.core.Object with .APIRequest',
            r'.dart.core.Object with .APIRequest',
            134218311,
            3,
            const prefix0.MyReflectable(),
            const <int>[0, 17, 30, 31, 20],
            const <int>[12, 13, 14, 15, 16, 17, 18, 19, 30, 31, 20],
            const <int>[],
            -1,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'dio', 134348805, -1,
            const prefix0.MyReflectable(), -1, 4, 4, null, null),
        r.VariableMirrorImpl(r'foto', 134349829, 1,
            const prefix0.MyReflectable(), -1, 5, 5, null, null),
        r.VariableMirrorImpl(r'nome', 134349829, 2,
            const prefix0.MyReflectable(), -1, 5, 5, null, null),
        r.VariableMirrorImpl(r'matricula', 134349829, 2,
            const prefix0.MyReflectable(), -1, 5, 5, null, null),
        r.VariableMirrorImpl(r'email', 134349829, 2,
            const prefix0.MyReflectable(), -1, 5, 5, null, null),
        r.VariableMirrorImpl(r'foto', 134349829, 2,
            const prefix0.MyReflectable(), 1, 1, 1, null, null),
        r.MethodMirrorImpl(r'login', 35651586, 0, -1, 6, 7, null,
            const <int>[0], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'instance', 2097171, 0, 0, 0, 0, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'foto', 2097155, 0, -1, 8, 8, null, const <int>[],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'usuario', 2097155, 0, -1, 9, 9, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'baseUrlProd', 2097155, 0, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'baseUrlDev', 2097155, 0, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 10, 10, null, const <int>[1],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[2], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 11, 11, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 12, 12, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'get', 35651586, -1, -1, 13, 14, null,
            const <int>[3, 4, 5], const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 0, 18),
        r.ImplicitSetterMirrorImpl(const prefix0.MyReflectable(), 0, 19),
        r.MethodMirrorImpl(r'baseUrl', 2097155, -1, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 1, 21),
        r.MethodMirrorImpl(r'', 0, 1, -1, 1, 1, null, const <int>[7],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 1, -1, 1, 1, null, const <int>[8],
            const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 2, 24),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 3, 25),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 4, 26),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 5, 27),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, null,
            const <int>[9, 10, 11, 12], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 2, -1, 2, 2, null, const <int>[13],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'baseUrlProd', 2097155, -1, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'baseUrlDev', 2097155, -1, -1, 5, 5, null,
            const <int>[], const prefix0.MyReflectable(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'authCookies',
            134356998,
            6,
            const prefix0.MyReflectable(),
            -1,
            5,
            5,
            null,
            null,
            null,
            #authCookies),
        r.ParameterMirrorImpl(r'other', 134348806, 12,
            const prefix0.MyReflectable(), -1, 15, 15, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 14,
            const prefix0.MyReflectable(), -1, 16, 16, null, null, null, null),
        r.ParameterMirrorImpl(r'path', 134356998, 17,
            const prefix0.MyReflectable(), -1, 5, 5, null, null, null, #path),
        r.ParameterMirrorImpl(
            r'queryParameters',
            84029446,
            17,
            const prefix0.MyReflectable(),
            -1,
            17,
            18,
            null,
            null,
            null,
            #queryParameters),
        r.ParameterMirrorImpl(
            r'options',
            67252230,
            17,
            const prefix0.MyReflectable(),
            -1,
            19,
            19,
            null,
            null,
            null,
            #options),
        r.ParameterMirrorImpl(r'_dio', 134348902, 19,
            const prefix0.MyReflectable(), -1, 4, 4, null, null, null, null),
        r.ParameterMirrorImpl(r'foto', 134358022, 22,
            const prefix0.MyReflectable(), -1, 5, 5, null, null, null, #foto),
        r.ParameterMirrorImpl(r'json', 151126022, 23,
            const prefix0.MyReflectable(), -1, 20, 21, null, null, null, null),
        r.ParameterMirrorImpl(r'nome', 134358022, 28,
            const prefix0.MyReflectable(), -1, 5, 5, null, null, null, #nome),
        r.ParameterMirrorImpl(
            r'matricula',
            134358022,
            28,
            const prefix0.MyReflectable(),
            -1,
            5,
            5,
            null,
            null,
            null,
            #matricula),
        r.ParameterMirrorImpl(r'email', 134358022, 28,
            const prefix0.MyReflectable(), -1, 5, 5, null, null, null, #email),
        r.ParameterMirrorImpl(r'foto', 134358022, 28,
            const prefix0.MyReflectable(), 1, 1, 1, null, null, null, #foto),
        r.ParameterMirrorImpl(r'json', 151126022, 29,
            const prefix0.MyReflectable(), -1, 20, 21, null, null, null, null)
      ],
      <Type>[
        prefix0.APIClient,
        prefix0.Foto,
        prefix0.Usuario,
        const r.FakeType(r'.dart.core.Object with .APIRequest'),
        prefix1.Dio,
        String,
        const m.TypeValue<prefix2.Future<void>>().type,
        prefix2.Future,
        prefix0.FotoService,
        prefix0.UsuarioService,
        bool,
        int,
        Type,
        const r.FakeType(r'dart.async.Future<T>'),
        prefix2.Future,
        Object,
        Invocation,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        prefix3.Options,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map
      ],
      4,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'get': (dynamic instance) => instance.get,
        r'dio': (dynamic instance) => instance.dio,
        r'baseUrlProd': (dynamic instance) => instance.baseUrlProd,
        r'baseUrlDev': (dynamic instance) => instance.baseUrlDev,
        r'baseUrl': (dynamic instance) => instance.baseUrl,
        r'login': (dynamic instance) => instance.login,
        r'foto': (dynamic instance) => instance.foto,
        r'usuario': (dynamic instance) => instance.usuario,
        r'nome': (dynamic instance) => instance.nome,
        r'matricula': (dynamic instance) => instance.matricula,
        r'email': (dynamic instance) => instance.email
      },
      {r'dio=': (dynamic instance, value) => instance.dio = value},
      null,
      [])
};

const _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
